# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/user_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1225, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1225, 851))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1225, 851))
        self.label.setStyleSheet("image: url(:/images/Static/background.webp);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/Static/background.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(360, 40, 521, 771))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"background-color: rgb(85, 170, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.header = QtWidgets.QLabel(self.frame_2)
        self.header.setGeometry(QtCore.QRect(160, 50, 191, 51))
        self.header.setStyleSheet("font: 25 20pt \"Segoe UI Light\";\n"
"text-decoration: underline;")
        self.header.setObjectName("header")
        self.firstnamelabel = QtWidgets.QLabel(self.frame_2)
        self.firstnamelabel.setGeometry(QtCore.QRect(50, 120, 151, 31))
        self.firstnamelabel.setObjectName("firstnamelabel")
        self.Lastnamelabel = QtWidgets.QLabel(self.frame_2)
        self.Lastnamelabel.setGeometry(QtCore.QRect(50, 220, 151, 31))
        self.Lastnamelabel.setObjectName("Lastnamelabel")
        self.emaillabel = QtWidgets.QLabel(self.frame_2)
        self.emaillabel.setGeometry(QtCore.QRect(50, 310, 151, 31))
        self.emaillabel.setObjectName("emaillabel")
        self.motdepasselabel = QtWidgets.QLabel(self.frame_2)
        self.motdepasselabel.setGeometry(QtCore.QRect(50, 410, 151, 31))
        self.motdepasselabel.setObjectName("motdepasselabel")
        self.confrimelabel = QtWidgets.QLabel(self.frame_2)
        self.confrimelabel.setGeometry(QtCore.QRect(50, 520, 251, 31))
        self.confrimelabel.setObjectName("confrimelabel")
        self.firstnameline = QtWidgets.QLineEdit(self.frame_2)
        self.firstnameline.setGeometry(QtCore.QRect(50, 160, 391, 41))
        self.firstnameline.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:none;")
        self.firstnameline.setObjectName("firstnameline")
        self.lastnameline = QtWidgets.QLineEdit(self.frame_2)
        self.lastnameline.setGeometry(QtCore.QRect(50, 260, 391, 41))
        self.lastnameline.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:none;")
        self.lastnameline.setObjectName("lastnameline")
        self.emailline = QtWidgets.QLineEdit(self.frame_2)
        self.emailline.setGeometry(QtCore.QRect(50, 350, 391, 41))
        self.emailline.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:none;")
        self.emailline.setObjectName("emailline")
        self.motdepasseline = QtWidgets.QLineEdit(self.frame_2)
        self.motdepasseline.setGeometry(QtCore.QRect(50, 460, 391, 41))
        self.motdepasseline.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:none;")
        self.motdepasseline.setObjectName("motdepasseline")
        self.confrimeline = QtWidgets.QLineEdit(self.frame_2)
        self.confrimeline.setGeometry(QtCore.QRect(50, 560, 391, 41))
        self.confrimeline.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border-radius:none;")
        self.confrimeline.setObjectName("confrimeline")
        self.sumbit_btn = QtWidgets.QPushButton(self.frame_2)
        self.sumbit_btn.setGeometry(QtCore.QRect(180, 680, 131, 41))
        self.sumbit_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius:none;")
        self.sumbit_btn.setAutoDefault(False)
        self.sumbit_btn.setDefault(True)
        self.sumbit_btn.setFlat(False)
        self.sumbit_btn.setObjectName("sumbit_btn")
        self.correction = QtWidgets.QLabel(self.frame_2)
        self.correction.setGeometry(QtCore.QRect(50, 630, 391, 41))
        self.correction.setText("")
        self.correction.setObjectName("correction")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Inscription</p></body></html>"))
        self.firstnamelabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">First Name </span></p></body></html>"))
        self.Lastnamelabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Last Name </span></p></body></html>"))
        self.emaillabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Email</span></p></body></html>"))
        self.motdepasselabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Mot de passe</span></p></body></html>"))
        self.confrimelabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Confirme mot de passe</span></p></body></html>"))
        self.sumbit_btn.setText(_translate("MainWindow", "Sumbit"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
